services:
  postgres:
    image: postgres:16
    container_name: notifyflow-postgres
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: notifyflow
      POSTGRES_PASSWORD: notifyflow
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: notifyflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
