plugins {
    id 'application'
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:3.3.5')

    implementation project(':notification-domain')
    implementation project(':notification-application')
    implementation project(':notification-api')
    implementation project(':notification-infrastructure')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

application {
    mainClass = 'com.notifyflow.bootstrap.NotifyflowApplication'
}
